api_platform:
    title: 'byArno API'
    description: 'API pour le configurateur 3D de produits artisanaux'
    version: '1.0.0'
    show_webby: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
    # Enable CORS
    cors_enabled: true
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 10
